version: '3.4'

services:
  transferdb:
    image: mongo  

  rabbitmq:
    image: rabbitmq:3-management-alpine  

  processing.api:
    image: ${DOCKER_REGISTRY-}processingapi
    build:
      context: .
      dockerfile: src/Services/Processing/Processing.API/Dockerfile

  transfer.api:
    image: ${DOCKER_REGISTRY-}transferapi
    build:
      context: .
      dockerfile: src/Services/Transfer/Transfer.API/Dockerfile

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2

  kibana:
    image: docker.elastic.co/kibana/kibana:7.9.2

volumes:
  mongo_data:
  elasticsearch-data: